# Week 2 - Preprocessing - Part 2
Keshia-Lee Martin<br>
OMDS-ModB2<br>
Media and Entertainment<br>

Datasets: <br>
[Movielens](https://grouplens.org/datasets/movielens/latest/), [Dataset Details](https://files.grouplens.org/datasets/movielens/ml-latest-small-README.html)<br>
[4 Services Streaming Movies and Tv](https://www.kaggle.com/datasets/sc0v1n0/4-services-streaming-movies-and-tv/data)

# Weekly graph question

The Storytelling With Data book mentions planning on a "Who, What, and How" for your data story.  Write down a possible Who, What, and How for your data, using the ideas in the book.

# Homework 2

In [2]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

## Movielens Dataset

The MovieLens dataset provides large-scale user-generated ratings, tags, and viewing preferences that capture audience sentiment, movie
popularity, and behavioral patterns associated with consumer engagement.

In [3]:
# creating DataFrames/variables for each csv file to understand the data in each file before combining
df_movie_links = pd.read_csv("movielens-links.csv")

df_movie_links.info()
print()
df_movie_links.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   imdbId   9742 non-null   int64
 2   tmdbId   9734 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 228.5 KB

             movieId        imdbId         tmdbId
count    9742.000000  9.742000e+03    9734.000000
mean    42200.353623  6.771839e+05   55162.123793
std     52160.494854  1.107228e+06   93653.481487
min         1.000000  4.170000e+02       2.000000
25%      3248.250000  9.518075e+04    9665.500000
50%      7300.000000  1.672605e+05   16529.000000
75%     76232.000000  8.055685e+05   44205.750000
max    193609.000000  8.391976e+06  525662.000000

In [4]:
df_movie_names = pd.read_csv("movielens-movies.csv")

df_movie_names.info()
print()
df_movie_names.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

             movieId
count    9742.000000
mean    42200.353623
std     52160.494854
min         1.000000
25%      3248.250000
50%      7300.000000
75%     76232.000000
max    193609.000000

In [5]:
# movie ratings by users
df_movie_ratings = pd.read_csv("movielens-ratings.csv")

df_movie_ratings.info()
print()
df_movie_ratings.describe() 
# based on data, need to check if the movieids are unique in the dataset.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

              userId        movieId         rating     timestamp
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

In [6]:
# users tags of the movies
df_movie_tags = pd.read_csv("movielens-tags.csv")

df_movie_tags.info()
print()
df_movie_tags.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3683 entries, 0 to 3682
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   userId     3683 non-null   int64
 1   movieId    3683 non-null   int64
 2   tag        3683 non-null   object
 3   timestamp  3683 non-null   int64
dtypes: int64(3), object(1)
memory usage: 115.2+ KB

            userId        movieId     timestamp
count  3683.000000    3683.000000  3.683000e+03
mean    431.149335   27252.013576  1.320032e+09
std     158.472553   43490.558803  1.721025e+08
min       2.000000       1.000000  1.137179e+09
25%     424.000000    1262.500000  1.137521e+09
50%     474.000000    4454.000000  1.269833e+09
75%     477.000000   39263.000000  1.498457e+09
max     610.000000  193565.000000  1.537099e+09

In [7]:
# combining the movie links csv and the movie titles csvs first
links_name_merged = df_movie_links.merge(df_movie_names, on='movieId', how='outer')
links_name_merged.head()

,movieId,imdbId,tmdbId,title,genres
0,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,113497,8844.0,Jumanji (1995),Adventure|Children|Fantasy
2,3,113228,15602.0,Grumpier Old Men (1995),Comedy|Romance
3,4,114885,31357.0,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,113041,11862.0,Father of the Bride Part II (1995),Comedy

In [8]:
# combined the ratings csv with the the movie tags csv
ratings_tags_merged = df_movie_ratings.merge(df_movie_tags, on='movieId', how='outer')
ratings_tags_merged.sample(5)

,userId_x,movieId,rating,timestamp_x,userId_y,tag,timestamp_y
12257,288.0,153,2.0,9.784666e+08,474.0,superhero,1.137375e+09
88793,490.0,356,3.5,1.324372e+09,567.0,bittersweet,1.525288e+09
187454,215.0,3448,4.5,1.260909e+09,NaN,NaN,NaN
154702,325.0,2268,3.0,1.039397e+09,474.0,court,1.137192e+09
30462,24.0,296,4.0,1.458942e+09,599.0,stylish,1.498456e+09

In [9]:
# merged previous combined csvs together
df_merge_movies = links_name_merged.merge(ratings_tags_merged, on='movieId', how='outer')
df_merge_movies.sample(5)

,movieId,imdbId,tmdbId,title,genres,userId_x,rating,timestamp_x,userId_y,tag,timestamp_y
36952,296,110912,680.0,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,100.0,3.5,1.100185e+09,599.0,Quentin Tarantino,1.498456e+09
235178,8957,387564,176.0,Saw (2004),Horror|Mystery|Thriller,212.0,2.5,1.523217e+09,125.0,clever,1.474382e+09
43568,296,110912,680.0,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,167.0,3.0,1.154723e+09,599.0,disturbing,1.498457e+09
61182,296,110912,680.0,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,348.0,5.0,1.378851e+09,599.0,motherfucker,1.498456e+09
33983,296,110912,680.0,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,63.0,5.0,1.443201e+09,599.0,episodic,1.498457e+09

Based on the html details about the data, the timestamps represent seconds since midnight Coordinated Universal Time (UTC) of January 1, 1970. There is no needs for this for our data. The timestamp columns need to be dropped.

In [10]:
df_merge_movies = df_merge_movies.drop('timestamp_x', axis=1)
df_merge_movies = df_merge_movies.drop('timestamp_y', axis=1)

Renaming columns userid_x and userid_y to know that which id is for the rating and which user is for the tagging of the movie.

In [11]:
df_merge_movies = df_merge_movies.rename(columns={'userId_x':'userId_rating'})
df_merge_movies = df_merge_movies.rename(columns={'userId_y':'userId_tag'})

Now, verifying that the columns were dropped and the columns were renamed.

In [39]:
df_merge_movies.sample(5)

,movieId,imdbId,tmdbId,title,genres,userId_rating,rating,userId_tag,tag
260462,69844,417741,767.0,Harry Potter and the Half-Blood Prince (2009),Adventure|Fantasy|Mystery|Romance|IMAX,318.0,3.5,NaN,NaN
235326,8957,387564,176.0,Saw (2004),Horror|Mystery|Thriller,573.0,4.5,125.0,Disturbing
206882,4878,246578,141.0,Donnie Darko (2001),Drama|Mystery|Sci-Fi|Thriller,448.0,4.0,193.0,surreal
64618,296,110912,680.0,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller,385.0,4.0,599.0,mobster
271611,89745,848228,24428.0,"Avengers, The (2012)",Action|Adventure|Sci-Fi|IMAX,601.0,4.5,537.0,silly

The following steps, there will be checking for duplicate rows, missing or null values.

In [13]:
df_merge_movies.info()
print()
df_merge_movies.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 285783 entries, 0 to 285782
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   movieId        285783 non-null  int64
 1   imdbId         285783 non-null  int64
 2   tmdbId         285770 non-null  float64
 3   title          285783 non-null  object
 4   genres         285783 non-null  object
 5   userId_rating  285762 non-null  float64
 6   rating         285762 non-null  float64
 7   userId_tag     233234 non-null  float64
 8   tag            233234 non-null  object
dtypes: float64(4), int64(2), object(3)
memory usage: 19.6+ MB

,movieId,imdbId,tmdbId,userId_rating,rating,userId_tag
count,285783.000000,2.857830e+05,285770.000000,285762.000000,285762.000000,233234.000000
mean,14927.663741,2.956050e+05,12797.315320,313.894279,3.841270,470.681354
std,31402.673519,5.150156e+05,43479.255523,179.451387,1.020798,153.324249
min,1.000000,4.170000e+02,2.000000,1.000000,0.500000,2.000000
25%,296.000000,1.098300e+05,489.000000,160.000000,3.000000,424.000000
50%,1721.000000,1.125730e+05,680.000000,314.000000,4.000000,477.000000
75%,5673.000000,2.415270e+05,8963.000000,465.000000,4.500000,599.000000
max,193609.000000,8.391976e+06,525662.000000,610.000000,5.000000,610.000000

In [14]:
# checking for duplicate rows
duplicated_rows = df_merge_movies[df_merge_movies.duplicated()]
duplicated_rows

Empty DataFrame
Columns: [movieId, imdbId, tmdbId, title, genres, userId_rating, rating, userId_tag, tag]
Index: []

In [37]:
# checking for missing or null values
df_merge_movies_null = df_merge_movies[df_merge_movies.isnull().any(axis=1)]
df_merge_movies_null.sample(5)

,movieId,imdbId,tmdbId,title,genres,userId_rating,rating,userId_tag,tag
223723,7084,69097,11610.0,"Play It Again, Sam (1972)",Comedy|Romance,448.0,3.0,NaN,NaN
181206,2993,59800,660.0,Thunderball (1965),Action|Adventure|Thriller,599.0,3.0,NaN,NaN
104829,637,117608,9099.0,Sgt. Bilko (1996),Comedy,169.0,4.5,NaN,NaN
283658,142488,1895587,314365.0,Spotlight (2015),Thriller,599.0,3.5,NaN,NaN
186790,3392,98309,11157.0,She-Devil (1989),Comedy,599.0,1.0,NaN,NaN

Based on the findings above, some movies did not have a user that gave the movie a tag. I think these empty values can be ignored.

In [16]:
# mean, median, mode of rating, the only column it would make sense to do this for
ratings_mean = df_merge_movies['rating'].mean()
ratings_median = df_merge_movies['rating'].median()
ratings_mode = df_merge_movies['rating'].mode()[0]

print(f"Movie ratings mean: {ratings_mean}")
print(f"Movie ratings median: {ratings_median}")
print(f"Movie ratings mode: {ratings_mode}")

Movie ratings mean: 3.8412700079086792
Movie ratings median: 4.0
Movie ratings mode: 4.0

In [36]:
# categorical variables with one hot encoding
# look at value as a string, separate each string by the separator
one_hot = df_merge_movies['genres'].str.get_dummies(sep='|')
one_hot

,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
4,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285778,0,1,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
285779,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
285780,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
285781,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
285782,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [26]:
# making a duplicate of the merged movies dataframe so it doesn't accidently change the original
df_merge_movies_final = df_merge_movies.copy()
df_merge_movies_final = df_merge_movies_final.join(one_hot)

In [27]:
# make and saving a new csv of the final data set (will not drop the original genre column)
df_merge_movies_final.to_csv('merged_movies_v1.csv', index=False)

## Conclusion

- This data is usable. 

- The timestamps added no significant value to the data. They identified when the data was submitted into the csv.

- The movie tags have a significantly lower amount of data, which only had 58 users that submitted tags across multiple movies. Therefore, many movies did not have tags and have empty values in those columns. At first glance, there doesn't seem to be any major issue because of the missing values.

Next steps:
- split the title column by the paranthesis and get a column for the year for additional analysis.
- drop the original genres column.

## Streaming Movies and TV Dataset

The 4 Services Streaming Movies and TV dataset adds a platform and content-distribution perspective through metadata on films and television content available across Netflix, Hulu, Prime Video, and Disney+, including genre, release year, age rating, and IMDb scores linked to streaming platform strategy and audience accessibility.

In [34]:
# creating df for each csv - looking at each csv and getting info and descriptions
df_streaming = pd.read_csv("all_streaming.csv")
# df_streaming

In [33]:
df_streaming_genre = pd.read_csv("all_genre.csv")
# df_streaming_genre

In [32]:
# combining the data sets
df_movie_tv_streaming = df_streaming.join(df_streaming_genre)
df_movie_tv_streaming

,movie_or_serie,title,director,cast,country,date_added_platform,release_year,duration_seconds,gender_type,description,...,medical,night,policecop,sketch,soap,spyespionage,survival,opera,travel,melodrama
0,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",uninformed country,"November 26, 2021",2016,23 min,animation>family,Join Mickey and the gang as they duck the halls!,...,0,0,0,0,0,0,0,0,0,0
1,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",uninformed country,"November 26, 2021",1988,91 min,comedy,Santa Claus passes his magic bag to a new St. ...,...,0,0,0,0,0,0,0,0,0,0
2,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,23 min,animation>comedy>family,Sid the Sloth is on Santa's naughty list.,...,0,0,0,0,0,0,0,0,0,0
3,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",uninformed country,"November 26, 2021",2021,41 min,musical,"This is real life, not just fantasy!",...,0,0,0,0,0,0,0,0,0,0
4,TV Show,The Beatles: Get Back,uninformed director,"John Lennon, Paul McCartney, George Harrison, ...",uninformed country,"November 25, 2021",2021,1 Season,docuseries>historical>music,A three-part documentary from Peter Jackson ca...,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22993,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",uninformed country,NaN,1940,60 min,comedy,New York City street principles get an East Si...,...,0,0,0,0,0,0,0,0,0,0
22994,TV Show,Planet Patrol,uninformed director,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",uninformed country,NaN,2018,4 Seasons,s,"This is Earth, 2100AD - and these are the adve...",...,0,0,0,0,0,0,0,0,0,0
22995,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",uninformed country,NaN,2008,90 min,action,"In war-torn Eastern Europe, a world-weary grou...",...,0,0,0,0,0,0,0,0,0,0
22996,TV Show,Maradona: Blessed Dream,uninformed director,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",uninformed country,NaN,2021,1 Season,drama>sports,"The series tells the story of Diego Maradona, ...",...,0,0,0,0,0,0,0,0,0,0
22997,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",uninformed country,NaN,2010,103 min,action>drama>suspense,"Harry Brown, starring two-time Academy Award w...",...,0,0,0,0,0,0,0,0,0,0

Conclusion

- Are the data usable?  If not, find some new data!

- Do you need to modify or correct the data in some way?

- Is there any class imbalance?  (Categories that have many more items than other categories)..

This week, you will do the same types of exercises as last week, but you should use your chosen datasets that someone in your class found last semester. (They likely will not be the particular datasets that you found yourself.)

### Here are some types of analysis you can do  Use Google, documentation, and ChatGPT to help you:

- Summarize the datasets using info() and describe()

- Are there any duplicate rows?

- Are there any duplicate values in a given column (when this would be inappropriate?)

- What are the mean, median, and mode of each column?

- Are there any missing or null values?

    - Do you want to fill in the missing value with a mean value?  A value of your choice?  Remove that row?

- Identify any other inconsistent data (e.g. someone seems to be taking an action before they are born.)

- Encode any categorical variables (e.g. with one-hot encoding.)

### Conclusions:

- Are the data usable?  If not, find some new data!

- Do you need to modify or correct the data in some way?

- Is there any class imbalance?  (Categories that have many more items than other categories).

# 4. Storytelling With Data graph

Just like last week: choose any graph in the Introduction of Storytelling With Data (p. 1-17). Use matplotlib to reproduce it in a rough way. I don't expect you to spend an enormous amount of time on this; I understand that you likely will not have time to re-create every feature of the graph. However, if you're excited about learning to use matplotlib, this is a good way to do that. You don't have to duplicate the exact values on the graph; just the same rough shape will be enough.  If you don't feel comfortable using matplotlib yet, do the best you can and write down what you tried or what Google searches you did to find the answers.